name: Rust-build

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/cache@v3
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
            - name: Build
              run: cargo build --verbose
            - name: Tests
              run: cargo test --verbose
